### ISSUE TITLE
Oralius' Whispering Crystal fails to rebuff on r18

### ISSUE THREAD

**Issue by speedwaystar** [Softrix/SmartBuff-Retail#12]
(from discord user MrWizard) SmartBuff Retail works on version r16 but r17 and r18 are failing to detect missing buffs (and thus rebuff) my character. I'm mostly testing on a hunter and the buff i want it to do is the Oralius' Whispering Crystal... and it's the only buff i've got checked
https://discord.com/channels/697774223833170000/859491029039579168/1070110029446909972

**Comment by ynazar1** [comment]
It's actually any buff for me. The addon loads but fails to detect any missing buff... If i only enable some potion or aspect of the cheetah for example, same thing happens, no detection  no rebuff. Similarly with other characters. The addon clearly loads but doesn't detect missing buffs.

**Comment by speedwaystar** [comment]
that's quite odd. have you done a complete reset of the addon’s internals?

![](https://i.imgur.com/WnIdIqX.png)

and, you're using r18.240123, right?

**Comment by ynazar1** [comment]
I really don't want to... with something like 40 alts i have that i'd need to reconfigure for. I'll try doing a full reset tonight i guess and see what develops.

**Comment by speedwaystar** [comment]
you absolutely have to do a reset (just of the addon), so it can rebuild its internal logic. the save file information is completely outdated and is basically nonsense to the latest version.

**Comment by ynazar1** [comment]
Quick sneak attempt... Looks like full reset did it... But this confirms that reset isn't not being forced by the application. It should be noted that I probably have SB data dating all the way to (possibly) Wrath of the Lich King (though I've likely reset at least once since then), but I've definitely not done a full reset myself for... solid close to a decade.

**Comment by speedwaystar** [comment]
cheers, i'll close the ticket then.
