### ISSUE TITLE
levelling doesn't trigger a refresh of known spells

### ISSUE THREAD

**Issue by speedwaystar** [Softrix/SmartBuff-Retail#18]
this occurs because the code no longer reinitializes itself every 3 seconds like it used to (!), but is now asynchronous and relies on OnEvent triggers. accordingly, we need to add an PLAYER_LEVEL_UP OnEvent call to SMARTBUFF_SetBuffs()

**Comment by ynazar1** [comment]
Note for later: 

register event and add it to the if statement at around line 706 in smartbuff.lua
