### ISSUE TITLE
bad argument #2 to '?' (Usage: local success = C_CVar.SetCVar(name [, value]))

### ISSUE THREAD

**Issue by Tlazolteotl** [Softrix/SmartBuff-Retail#26]
Message: bad argument #2 to '?' (Usage: local success = C_CVar.SetCVar(name [, value]))
Time: Fri May 12 10:51:11 2023
Count: 1
Stack: bad argument #2 to '?' (Usage: local success = C_CVar.SetCVar(name [, value]))
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@Interface/AddOns/SmartBuff/SmartBuff.lua"]:2274: in function `SMARTBUFF_BuffUnit'
[string "@Interface/AddOns/SmartBuff/SmartBuff.lua"]:1674: in function `SMARTBUFF_Check'
[string "@Interface/AddOns/SmartBuff/SmartBuff.lua"]:726: in function `SMARTBUFF_OnUpdate'
[string "*SmartBuff.xml:41_OnUpdate"]:1: in function <[string "*SmartBuff.xml:41_OnUpdate"]:1>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by speedwaystar** [comment]
https://github.com/Softrix/SmartBuff-Retail/pull/27
